#include "virtual_machine/handlers/vm_handlers/vm_enter.h"
#include "virtual_machine/handlers/vm_handlers/vm_exit.h"
#include "virtual_machine/handlers/vm_handlers/vm_load.h"
#include "virtual_machine/handlers/vm_handlers/vm_pop.h"
#include "virtual_machine/handlers/vm_handlers/vm_push.h"
#include "virtual_machine/handlers/vm_handlers/vm_store.h"