#include "virtual_machine/handlers/ia32_handlers/add.h"
#include "virtual_machine/handlers/ia32_handlers/dec.h"
#include "virtual_machine/handlers/ia32_handlers/div.h"
#include "virtual_machine/handlers/ia32_handlers/mul.h"
#include "virtual_machine/handlers/ia32_handlers/sub.h"